import { useCallback, useEffect, useState, type ChangeEvent } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { X, BookUser, Loader2, Printer, Download } from 'lucide-react';
import { jsPDF } from 'jspdf';

/**
 * Ocean — Bio-Data Auto Builder (Feature 218)
 * ---------------------------------------------
 * Build a marriage bio-data and export a REAL PDF download (jsPDF) or print.
 * Backed by /api/profile/biodata.
 */

interface BioDataBuilderProps {
  token: string | null;
  currentUser: { id: string; name: string } | null;
  onClose: () => void;
}

interface BioData {
  name: string; dob: string; height: string; education: string; occupation: string;
  city: string; religion: string; familyInfo: string; preferences: string;
}

const EMPTY: BioData = { name: '', dob: '', height: '', education: '', occupation: '', city: '', religion: '', familyInfo: '', preferences: '' };

/** Build and download a real A4 bio-data PDF with jsPDF. */
export function buildBioDataPdf(b: BioData): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const M = 18, W = 174;
  let y = 26;

  doc.setFillColor(210, 180, 140);
  doc.rect(0, 0, 210, 14, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(13);
  doc.setTextColor(40);
  doc.text('BIO-DATA', 105, 9, { align: 'center' });
  doc.setTextColor(25);

  doc.setFontSize(20);
  doc.text(b.name || 'Name', M, y);
  y += 8;

  const row = (label: string, value: string) => {
    if (!value) return;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(120);
    doc.text(label.toUpperCase(), M, y);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(30);
    // Values start at x = M + 52 — wrap to the actual available width so long
    // text never overflows the right margin.
    const lines = doc.splitTextToSize(value, W - 52) as string[];
    doc.text(lines, M + 52, y);
    y += lines.length * 5 + 2.5;
    if (y > 282) { doc.addPage(); y = 22; }
  };

  row('Date of birth', b.dob);
  row('Height', b.height);
  row('Education', b.education);
  row('Occupation', b.occupation);
  row('City', b.city);
  row('Religion / sect', b.religion);

  if (b.familyInfo) {
    y += 3;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(20, 70, 130);
    doc.text('FAMILY INFORMATION', M, y);
    y += 5;
    doc.setTextColor(30);
    const lines = doc.splitTextToSize(b.familyInfo, W) as string[];
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.text(lines, M, y);
    y += lines.length * 5 + 3;
  }

  if (b.preferences) {
    if (y > 270) { doc.addPage(); y = 22; }
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(20, 70, 130);
    doc.text('PARTNER PREFERENCES', M, y);
    y += 5;
    doc.setTextColor(30);
    const lines = doc.splitTextToSize(b.preferences, W) as string[];
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.text(lines, M, y);
  }

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text('Generated by Ocean Bio-Data Builder', M, 292);
  doc.save(`${(b.name || 'biodata').replace(/\s+/g, '_').replace(/[^\w-]/g, '')}_biodata.pdf`);
}

export default function BioDataBuilder({ token, currentUser, onClose }: BioDataBuilderProps) {
  const [visible, setVisible] = useState(true);
  const [b, setB] = useState<BioData>(EMPTY);
  const [html, setHtml] = useState('');
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);

  const toast = (message: string, variant?: string) =>
    window.dispatchEvent(new CustomEvent('show-toast', { detail: { message, variant } }));

  const authToken = token || localStorage.getItem('secure_auth_token');
  const api = async (path: string, method = 'GET', body?: unknown) => {
    const res = await fetch(path, {
      method,
      headers: { 'Content-Type': 'application/json', ...(authToken ? { Authorization: `Bearer ${authToken}` } : {}) },
      body: body ? JSON.stringify(body) : undefined,
    });
    if (!res.ok) {
      const err = await res.json().catch(() => ({}));
      throw new Error((err as any).error || `Request failed (${res.status})`);
    }
    return res.json();
  };

  const load = useCallback(async () => {
    if (!currentUser) { setLoading(false); return; }
    try {
      const d = await api(`/api/profile/biodata/${currentUser.id}`, 'GET');
      const { biodata } = d;
      setB({ name: biodata.name || '', dob: biodata.dob || '', height: biodata.height || '', education: biodata.education || '', occupation: biodata.occupation || '', city: biodata.city || '', religion: biodata.religion || '', familyInfo: biodata.familyInfo || '', preferences: biodata.preferences || '' });
      setHtml(d.html);
    } catch { /* ignore */ } finally { setLoading(false); }
  }, [currentUser]);

  useEffect(() => { load(); }, [load]);

  const save = async () => {
    setBusy(true);
    try {
      const d = await api('/api/profile/biodata', 'POST', b);
      setB({ name: d.biodata.name, dob: d.biodata.dob, height: d.biodata.height, education: d.biodata.education, occupation: d.biodata.occupation, city: d.biodata.city, religion: d.biodata.religion, familyInfo: d.biodata.familyInfo, preferences: d.biodata.preferences });
      setHtml(d.html);
      toast('Bio-data saved.');
    } catch (e: any) { toast(e.message || 'Save failed.', 'destructive'); } finally { setBusy(false); }
  };

  const printPdf = () => {
    const win = window.open('', '_blank');
    if (!win) return toast('Popup blocked.');
    win.document.write(html);
    win.document.close();
    win.focus();
    setTimeout(() => win.print(), 400);
  };

  const set = (k: keyof BioData) => (e: ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) =>
    setB({ ...b, [k]: e.target.value });

  const shell = 'fixed inset-0 z-[115] bg-[#141b2b]/55 dark:bg-[#05060c]/85 backdrop-blur-sm overflow-y-auto py-6 px-4';
  const card = 'bg-[#fcfaf4] dark:bg-zinc-900 border border-[#ebdcca] dark:border-zinc-800 rounded-3xl p-5 md:p-6 space-y-4 shadow-xs';
  const btnPrimary = 'flex items-center gap-1.5 px-3 py-2 rounded-xl bg-[#3a342a] text-[#f4f1ea] text-[10px] font-mono uppercase font-bold hover:bg-[#52493b] disabled:opacity-50';
  const input = 'w-full bg-white dark:bg-zinc-800 border border-[#ebdcca] dark:border-zinc-700 rounded-xl px-3 py-2 text-xs text-[#3a342a] dark:text-zinc-100 placeholder-[#8a8172]/60 outline-none focus:border-amber-400 transition-colors';

  const fields: { key: keyof BioData; label: string; full?: boolean }[] = [
    { key: 'name', label: 'Full name' }, { key: 'dob', label: 'Date of birth' },
    { key: 'height', label: 'Height' }, { key: 'education', label: 'Education' },
    { key: 'occupation', label: 'Occupation' }, { key: 'city', label: 'City' },
    { key: 'religion', label: 'Religion / sect' }, { key: 'familyInfo', label: 'Family information', full: true },
    { key: 'preferences', label: 'Partner preferences', full: true },
  ];

  return (
    <AnimatePresence onExitComplete={() => onClose()}>
      {visible && (
        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className={shell}>
          <div className="max-w-xl mx-auto">
            <div className="flex items-center justify-between mb-4">
              <span className="font-mono text-[10px] uppercase tracking-widest text-[#8a8172] dark:text-zinc-400">Bio-data</span>
              <button onClick={() => setVisible(false)} className="w-9 h-9 rounded-full bg-white/80 dark:bg-zinc-800 border border-[#ebdcca] dark:border-zinc-700 flex items-center justify-center text-[#5c5446] dark:text-zinc-300 hover:bg-[#ebdcca]/50 transition-all" aria-label="Close">
                <X size={16} />
              </button>
            </div>

            <div className={card}>
              <div className="flex items-center gap-2">
                <span className="w-9 h-9 rounded-full bg-teal-800/10 dark:bg-teal-400/10 flex items-center justify-center">
                  <BookUser className="text-teal-800 dark:text-teal-400" size={17} />
                </span>
                <div className="flex-1">
                  <h2 className="font-display text-lg font-bold text-[#3a342a] dark:text-zinc-100">Bio-Data Builder</h2>
                  <p className="font-mono text-[9px] uppercase tracking-wider text-[#8a8172] dark:text-zinc-400">Marriage bio-data · print-ready PDF</p>
                </div>
                {html && (
                  <div className="flex gap-1.5">
                    <button onClick={() => buildBioDataPdf(b)} className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-[#3a342a] text-[#f4f1ea] text-[10px] font-mono uppercase font-bold hover:bg-[#52493b]">
                      <Download size={11} /> Download PDF
                    </button>
                    <button onClick={printPdf} className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-white border border-[#cfcac0] dark:border-zinc-700 text-[10px] font-mono uppercase font-bold text-[#3a342a] dark:text-zinc-100 hover:bg-[#ebdcca]/40">
                      <Printer size={11} /> Print
                    </button>
                  </div>
                )}
              </div>

              {!currentUser ? (
                <p className="font-mono text-[10px] uppercase tracking-wide text-[#8a8172] dark:text-zinc-400 text-center py-6">Sign in to build your bio-data.</p>
              ) : loading ? (
                <div className="py-10 text-center font-mono text-[10px] uppercase tracking-wider text-[#8a8172] dark:text-zinc-400 flex items-center justify-center gap-2">
                  <Loader2 size={13} className="animate-spin" /> Loading…
                </div>
              ) : (
                <div className="space-y-2">
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                    {fields.map(f => (
                      f.full ? (
                        <textarea key={f.key} className={`${input} resize-none col-span-full`} rows={2} value={b[f.key]} onChange={set(f.key)} placeholder={f.label} />
                      ) : (
                        <input key={f.key} className={input} value={b[f.key]} onChange={set(f.key)} placeholder={f.label} />
                      )
                    ))}
                  </div>
                  <button onClick={save} disabled={busy} className={`${btnPrimary} w-full justify-center`}>
                    {busy ? <Loader2 size={11} className="animate-spin" /> : null} Save bio-data
                  </button>
                </div>
              )}
            </div>
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
