import { useCallback, useEffect, useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { X, FileText, Plus, Loader2, Printer, Eye, Download } from 'lucide-react';
import { jsPDF } from 'jspdf';

/**
 * Ocean — Resume Builder (Feature 194)
 * -------------------------------------
 * Edit resume details (skills, experience, education) and generate a REAL PDF
 * download (jsPDF) plus a print-ready HTML preview from your Ocean profile.
 * Backed by /api/profile/resume.
 */

interface ResumeBuilderProps {
  token: string | null;
  currentUser: { id: string; name: string } | null;
  onClose: () => void;
}

interface Resume {
  id: string; userId: string; name: string; headline: string; summary: string;
  skills: string[]; experience: { role: string; org: string; years: string; desc: string }[];
  education: { degree: string; school: string; year: string }[];
  contact: { email: string; phone: string; city: string };
}

const EMPTY: Resume = {
  id: '', userId: '', name: '', headline: '', summary: '',
  skills: [], experience: [], education: [], contact: { email: '', phone: '', city: '' },
};

/** Build and download a real A4 PDF resume with jsPDF. */
export function buildResumePdf(r: Resume): void {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const M = 16, W = 178;
  let y = 22;

  const ensure = (needed: number) => {
    if (y + needed > 285) { doc.addPage(); y = 20; }
  };
  const section = (title: string) => {
    ensure(12);
    y += 4;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(20, 70, 130);
    doc.text(title.toUpperCase(), M, y);
    y += 2;
    doc.setDrawColor(190);
    doc.line(M, y, M + W, y);
    y += 5;
    doc.setTextColor(30);
  };
  const para = (text: string, opts: { bold?: boolean; size?: number; color?: number[] } = {}) => {
    if (!text) return;
    doc.setFont('helvetica', opts.bold ? 'bold' : 'normal');
    doc.setFontSize(opts.size || 9.5);
    if (opts.color) doc.setTextColor(opts.color[0], opts.color[1], opts.color[2]);
    const lines = doc.splitTextToSize(text, W) as string[];
    ensure(lines.length * 4.5 + 3);
    doc.text(lines, M, y);
    y += lines.length * 4.5 + 1.5;
    doc.setTextColor(30);
  };

  // Header
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(24);
  doc.setTextColor(25);
  doc.text(r.name || 'Your Name', M, y);
  y += 8;
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(11.5);
  doc.setTextColor(90);
  doc.text(r.headline || '', M, y);
  y += 6;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(120);
  const contact = [r.contact.email, r.contact.phone, r.contact.city].filter(Boolean).join('  ·  ');
  if (contact) { doc.text(contact, M, y); y += 8; } else { y += 6; }

  section('Summary');
  para(r.summary);

  section('Experience');
  if (r.experience.length === 0) para('—');
  r.experience.forEach((e) => {
    para(`${e.role} — ${e.org}${e.years ? `  (${e.years})` : ''}`, { bold: true, size: 10 });
    para(e.desc);
    y += 2;
  });

  section('Education');
  if (r.education.length === 0) para('—');
  r.education.forEach((e) => {
    para(`${e.degree} — ${e.school}${e.year ? `  (${e.year})` : ''}`, { bold: true, size: 10 });
    y += 2;
  });

  section('Skills');
  para(r.skills.join(', ') || '—');

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text('Generated by Ocean Resume Builder', M, 292);
  doc.save(`${(r.name || 'resume').replace(/\s+/g, '_').replace(/[^\w-]/g, '')}.pdf`);
}

export default function ResumeBuilder({ token, currentUser, onClose }: ResumeBuilderProps) {
  const [visible, setVisible] = useState(true);
  const [r, setR] = useState<Resume>(EMPTY);
  const [html, setHtml] = useState('');
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [skills, setSkills] = useState('');
  const [expRole, setExpRole] = useState('');
  const [expOrg, setExpOrg] = useState('');
  const [expYears, setExpYears] = useState('');
  const [expDesc, setExpDesc] = useState('');
  const [eduDegree, setEduDegree] = useState('');
  const [eduSchool, setEduSchool] = useState('');
  const [eduYear, setEduYear] = useState('');

  const toast = (message: string, variant?: string) =>
    window.dispatchEvent(new CustomEvent('show-toast', { detail: { message, variant } }));

  const authToken = token || localStorage.getItem('secure_auth_token');
  const api = async (path: string, method = 'GET', body?: unknown) => {
    const res = await fetch(path, {
      method,
      headers: { 'Content-Type': 'application/json', ...(authToken ? { Authorization: `Bearer ${authToken}` } : {}) },
      body: body ? JSON.stringify(body) : undefined,
    });
    if (!res.ok) {
      const err = await res.json().catch(() => ({}));
      throw new Error((err as any).error || `Request failed (${res.status})`);
    }
    return res.json();
  };

  const load = useCallback(async () => {
    if (!currentUser) { setLoading(false); return; }
    try {
      const d = await api(`/api/profile/resume/${currentUser.id}`, 'GET');
      setR(d.resume);
      setHtml(d.html);
      setSkills((d.resume.skills || []).join(', '));
    } catch { /* default empty */ } finally { setLoading(false); }
  }, [currentUser]);

  useEffect(() => { load(); }, [load]);

  const save = async () => {
    setBusy(true);
    try {
      const d = await api('/api/profile/resume', 'POST', {
        name: r.name, headline: r.headline, summary: r.summary,
        skills: skills.split(',').map(s => s.trim()).filter(Boolean),
        experience: r.experience, education: r.education, contact: r.contact,
      });
      setR(d.resume);
      setHtml(d.html);
      toast('Resume saved.');
    } catch (e: any) { toast(e.message || 'Save failed.', 'destructive'); } finally { setBusy(false); }
  };

  const addExp = () => {
    if (!expRole.trim() || !expOrg.trim()) return toast('Role and org required.');
    setR({ ...r, experience: [...r.experience, { role: expRole, org: expOrg, years: expYears, desc: expDesc }] });
    setExpRole(''); setExpOrg(''); setExpYears(''); setExpDesc('');
  };

  const addEdu = () => {
    if (!eduDegree.trim() || !eduSchool.trim()) return toast('Degree and school required.');
    setR({ ...r, education: [...r.education, { degree: eduDegree, school: eduSchool, year: eduYear }] });
    setEduDegree(''); setEduSchool(''); setEduYear('');
  };

  const openPrint = () => {
    const win = window.open('', '_blank');
    if (!win) return toast('Popup blocked — allow popups for this site.');
    win.document.write(html);
    win.document.close();
    win.focus();
    setTimeout(() => win.print(), 400);
  };

  const shell = 'fixed inset-0 z-[115] bg-[#f6f1e7]/95 dark:bg-zinc-950/95 backdrop-blur-sm overflow-y-auto py-6 px-4';
  const card = 'bg-[#fcfaf4] dark:bg-zinc-900 border border-[#ebdcca] dark:border-zinc-800 rounded-3xl p-5 md:p-6 space-y-4 shadow-xs';
  const btnPrimary = 'flex items-center gap-1.5 px-3 py-2 rounded-xl bg-[#3a342a] text-[#f4f1ea] text-[10px] font-mono uppercase font-bold hover:bg-[#52493b] disabled:opacity-50';
  const input = 'w-full bg-white dark:bg-zinc-800 border border-[#ebdcca] dark:border-zinc-700 rounded-xl px-3 py-2 text-xs text-[#3a342a] dark:text-zinc-100 placeholder-[#8a8172]/60 outline-none focus:border-amber-400 transition-colors';

  return (
    <AnimatePresence onExitComplete={() => onClose()}>
      {visible && (
        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className={shell}>
          <div className="max-w-xl mx-auto">
            <div className="flex items-center justify-between mb-4">
              <span className="font-mono text-[10px] uppercase tracking-widest text-[#8a8172] dark:text-zinc-400">Resume builder</span>
              <button onClick={() => setVisible(false)} className="w-9 h-9 rounded-full bg-white/80 dark:bg-zinc-800 border border-[#ebdcca] dark:border-zinc-700 flex items-center justify-center text-[#5c5446] dark:text-zinc-300 hover:bg-[#ebdcca]/50 transition-all" aria-label="Close">
                <X size={16} />
              </button>
            </div>

            {!currentUser ? (
              <div className={card}><p className="font-mono text-[10px] uppercase tracking-wide text-[#8a8172] dark:text-zinc-400 text-center py-8">Sign in to build your resume.</p></div>
            ) : loading ? (
              <div className={`${card} text-center py-10 font-mono text-[10px] uppercase tracking-wider text-[#8a8172] dark:text-zinc-400`}><Loader2 size={13} className="animate-spin inline mr-2" /> Loading…</div>
            ) : (
              <div className={card}>
                <div className="flex items-center gap-2">
                  <span className="w-9 h-9 rounded-full bg-cyan-800/10 dark:bg-cyan-400/10 flex items-center justify-center">
                    <FileText className="text-cyan-800 dark:text-cyan-400" size={17} />
                  </span>
                  <div className="flex-1">
                    <h2 className="font-display text-lg font-bold text-[#3a342a] dark:text-zinc-100">Resume Builder</h2>
                    <p className="font-mono text-[9px] uppercase tracking-wider text-[#8a8172] dark:text-zinc-400">Print-ready PDF from your Ocean profile</p>
                  </div>
                  <div className="flex gap-1.5">
                    <button onClick={() => buildResumePdf(r)} className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-[#3a342a] text-[#f4f1ea] text-[10px] font-mono uppercase font-bold hover:bg-[#52493b]">
                      <Download size={11} /> Download PDF
                    </button>
                    <button onClick={openPrint} className="flex items-center gap-1.5 px-3 py-2 rounded-xl bg-white border border-[#cfcac0] dark:border-zinc-700 text-[10px] font-mono uppercase font-bold text-[#3a342a] dark:text-zinc-100 hover:bg-[#ebdcca]/40">
                      <Printer size={11} /> Print
                    </button>
                  </div>
                </div>

                <div className="space-y-2">
                  <input className={input} value={r.name} onChange={e => setR({ ...r, name: e.target.value })} placeholder="Full name" />
                  <input className={input} value={r.headline} onChange={e => setR({ ...r, headline: e.target.value })} placeholder="Headline" />
                  <textarea className={`${input} resize-none`} rows={2} value={r.summary} onChange={e => setR({ ...r, summary: e.target.value })} placeholder="Summary" />
                  <div className="grid grid-cols-2 gap-2">
                    <input className={input} value={r.contact.email} onChange={e => setR({ ...r, contact: { ...r.contact, email: e.target.value } })} placeholder="Email" />
                    <input className={input} value={r.contact.phone} onChange={e => setR({ ...r, contact: { ...r.contact, phone: e.target.value } })} placeholder="Phone" />
                    <input className={input} value={r.contact.city} onChange={e => setR({ ...r, contact: { ...r.contact, city: e.target.value } })} placeholder="City" />
                    <input className={input} value={skills} onChange={e => setSkills(e.target.value)} placeholder="Skills (comma separated)" />
                  </div>
                  <button onClick={save} disabled={busy} className={`${btnPrimary} justify-center w-full`}>
                    {busy ? <Loader2 size={11} className="animate-spin" /> : null} Save resume
                  </button>
                </div>

                <div className="rounded-2xl border border-[#ebdcca] dark:border-zinc-800 p-3 space-y-2">
                  <div className="font-mono text-[9px] uppercase font-bold tracking-wider text-[#5c5446] dark:text-zinc-300"><Plus size={11} className="inline" /> Add experience</div>
                  <div className="grid grid-cols-2 gap-2">
                    <input className={input} value={expRole} onChange={e => setExpRole(e.target.value)} placeholder="Role" />
                    <input className={input} value={expOrg} onChange={e => setExpOrg(e.target.value)} placeholder="Organization" />
                    <input className={input} value={expYears} onChange={e => setExpYears(e.target.value)} placeholder="Years (e.g. 2021–2024)" />
                  </div>
                  <input className={input} value={expDesc} onChange={e => setExpDesc(e.target.value)} placeholder="Description" />
                  <button onClick={addExp} className={`${btnPrimary} w-full justify-center`}><Plus size={11} /> Add experience</button>
                </div>

                <div className="rounded-2xl border border-[#ebdcca] dark:border-zinc-800 p-3 space-y-2">
                  <div className="font-mono text-[9px] uppercase font-bold tracking-wider text-[#5c5446] dark:text-zinc-300"><Plus size={11} className="inline" /> Add education</div>
                  <div className="grid grid-cols-2 gap-2">
                    <input className={input} value={eduDegree} onChange={e => setEduDegree(e.target.value)} placeholder="Degree" />
                    <input className={input} value={eduSchool} onChange={e => setEduSchool(e.target.value)} placeholder="School / university" />
                    <input className={input} value={eduYear} onChange={e => setEduYear(e.target.value)} placeholder="Year" />
                  </div>
                  <button onClick={addEdu} className={`${btnPrimary} w-full justify-center`}><Plus size={11} /> Add education</button>
                </div>

                <details className="rounded-2xl border border-[#ebdcca] dark:border-zinc-800 p-3">
                  <summary className="flex items-center gap-1.5 font-mono text-[9px] uppercase font-bold tracking-wider text-[#5c5446] dark:text-zinc-300 cursor-pointer">
                    <Eye size={11} /> Preview document
                  </summary>
                  <div className="mt-3 max-h-80 overflow-y-auto rounded-xl border border-[#ebdcca] dark:border-zinc-700 bg-white p-4 text-[10px] text-[#3a342a]" dangerouslySetInnerHTML={{ __html: html }} />
                </details>
              </div>
            )}
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}
